# Generated by Django 3.0.8 on 2020-07-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
