# Generated by Django 3.0.8 on 2020-07-17 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_album_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='track_list',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Details',
        ),
    ]
