# Generated by Django 3.0.8 on 2020-07-21 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0005_book'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='album',
            order_with_respect_to='title',
        ),
        migrations.AlterOrderWithRespectTo(
            name='book',
            order_with_respect_to='author',
        ),
    ]
